name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupération du code
      - uses: actions/checkout@v3

      # 2) Node.js 18 + cache npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3) Dépendances
      - run: npm ci

      # 4) Lint (enlève cette étape si tu n’as pas de script lint)
      - run: npm run lint

      # 5) Tests (enlève si tu n’as pas de tests)
      - run: npm run test -- --coverage

      # 6) Build Next.js
      #    Next chargera automatiquement ton .env.production
      - run: npm run build
