name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # ─── Injecte les variables dans GITHUB_ENV ───
      # DWOLLA_ENVIRONMENT et DWOLLA_ENV auront la même valeur
      - name: Export secrets to env
        run: |
          echo "DWOLLA_ENVIRONMENT=${{ secrets.DWOLLA_ENVIRONMENT }}" >> $GITHUB_ENV
          echo "DWOLLA_ENV=${{ secrets.DWOLLA_ENVIRONMENT }}"        >> $GITHUB_ENV

      - name: Install deps
        run: npm ci

      - name: Build (Next.js)
        run: npm run build
