name: CI - Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔐 Inject secrets into .env
        run: |
          echo "DWOLLA_ENVIRONMENT=${{ secrets.DWOLLA_ENVIRONMENT }}" >> .env
          echo "DWOLLA_API_KEY=${{ secrets.DWOLLA_API_KEY }}" >> .env
          echo "DWOLLA_API_SECRET=${{ secrets.DWOLLA_API_SECRET }}" >> .env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
          echo "PLAID_CLIENT_ID=${{ secrets.PLAID_CLIENT_ID }}" >> .env
          echo "PLAID_SECRET=${{ secrets.PLAID_SECRET }}" >> .env
          echo "PLAID_ENV=${{ secrets.PLAID_ENV }}" >> .env
          echo "PLAID_PRODUCTS=${{ secrets.PLAID_PRODUCTS }}" >> .env

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Lint the code
        run: npm run lint

      - name: 🏗 Build the app
        run: npm run build

      - name: 📊 SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
