name: CI - Build & Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: # 🌍 Variables d'environnement injectées depuis GitHub Secrets
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DWOLLA_ENVIRONMENT: ${{ secrets.DWOLLA_ENVIRONMENT }}
      DWOLLA_KEY: ${{ secrets.DWOLLA_KEY }}
      DWOLLA_SECRET: ${{ secrets.DWOLLA_SECRET }}
      DWOLLA_BASE_URL: ${{ secrets.DWOLLA_BASE_URL }}
      PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
      PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
      PLAID_ENV: ${{ secrets.PLAID_ENV }}
      PLAID_PRODUCTS: ${{ secrets.PLAID_PRODUCTS }}
      NEXT_APPWRITE_KEY: ${{ secrets.NEXT_APPWRITE_KEY }}
      APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}

    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🧹 Lint the code
        run: npm run lint

      - name: 🧪 Run tests and generate coverage
        run: npm run test -- --coverage

      - name: 🔍 SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # requis pour SonarCloud

      - name: 🏗️ Build the app
        run: npm run build
