name: CI - Build & Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: # 🌍 Variables d'environnement globales
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      NEXT_PUBLIC_DWOLLA_ENVIRONMENT=sandbox


    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🧹 Lint the code
        run: npm run lint

      - name: 🧪 Run tests and generate coverage
        run: npm run test -- --coverage

      - name: 🔍 SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # requis pour SonarCloud

      - name: 🏗️ Build the app
        run: npm run build
