name: CI - Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Inject secrets into .env
        run: |
          echo "DWOLLA_ENVIRONMENT=${{ secrets.DWOLLA_ENVIRONMENT }}" >> .env
          echo "DWOLLA_API_KEY=${{ secrets.DWOLLA_API_KEY }}" >> .env
          echo "DWOLLA_API_SECRET=${{ secrets.DWOLLA_API_SECRET }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
