name: CI - Build & Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: # ✅ VARIABLES GLOBAL POUR TOUS LES STEPS
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DWOLLA_ENVIRONMENT: ${{ secrets.DWOLLA_ENVIRONMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint the code
        run: npm run lint

      - name: Run tests and generate coverage
        run: npm run test -- --coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .

      - name: Build the app
        run: npm run build
